// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAG0MtLdeMKL14EgvAcjy6_iYUS5uccAk',
    appId: '1:593046029438:web:c97a9c5c9119f4d6a4c42f',
    messagingSenderId: '593046029438',
    projectId: 'vsing-database',
    authDomain: 'vsing-database.firebaseapp.com',
    storageBucket: 'vsing-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx51IAXd9_gtaDK7Y9tcQLJamRSm9eJTo',
    appId: '1:593046029438:android:fbade147226438f3a4c42f',
    messagingSenderId: '593046029438',
    projectId: 'vsing-database',
    storageBucket: 'vsing-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHLgYvqQ9KwiHOlpLO9h-u0r_UoPBWHd4',
    appId: '1:593046029438:ios:a6c90f62cc73bb88a4c42f',
    messagingSenderId: '593046029438',
    projectId: 'vsing-database',
    storageBucket: 'vsing-database.appspot.com',
    iosClientId: '593046029438-l27p3eugfmq5n9ietp4nofuqsiqqua3a.apps.googleusercontent.com',
    iosBundleId: '.In.rsv.op',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHLgYvqQ9KwiHOlpLO9h-u0r_UoPBWHd4',
    appId: '1:593046029438:ios:a6c90f62cc73bb88a4c42f',
    messagingSenderId: '593046029438',
    projectId: 'vsing-database',
    storageBucket: 'vsing-database.appspot.com',
    iosClientId: '593046029438-l27p3eugfmq5n9ietp4nofuqsiqqua3a.apps.googleusercontent.com',
    iosBundleId: '.In.rsv.op',
  );
}
